services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticketlemon-user-service
    ports:
      - "8002:8002"
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}
